/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/authenticated/route'
import { Route as ChildRouteImport } from './routes/child'
import { Route as AuthenticatedParentRouteImport } from './routes/authenticated/parent'
import { Route as ChildIndexRouteImport } from './routes/child.index'
import { Route as ChildBadgesRouteImport } from './routes/child.badges'
import { Route as ChildLearnRouteImport } from './routes/child.learn'
import { Route as ChildProgressRouteImport } from './routes/child.progress'
import { Route as ChildScenarioRouteImport } from './routes/child.scenario'
import { Route as ChildScenariosRouteImport } from './routes/child.scenarios'
import { Route as ChildSettingsRouteImport } from './routes/child.settings'
import { Route as ChildTalkRouteImport } from './routes/child.talk'
import { Route as AuthenticatedParentIndexRouteImport } from './routes/authenticated/parent.index'
import { Route as AuthenticatedParentAlertsRouteImport } from './routes/authenticated/parent.alerts'
import { Route as AuthenticatedParentChaptersRouteImport } from './routes/authenticated/parent.chapters'
import { Route as AuthenticatedParentControlsRouteImport } from './routes/authenticated/parent.controls'
import { Route as AuthenticatedParentPerformanceRouteImport } from './routes/authenticated/parent.performance'
import { Route as AuthenticatedParentPrivacyRouteImport } from './routes/authenticated/parent.privacy'
import { Route as AuthenticatedParentProfileRouteImport } from './routes/authenticated/parent.profile'
import { Route as AuthenticatedParentSettingsRouteImport } from './routes/authenticated/parent.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/authenticated',
  path: '/authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildRoute = ChildRouteImport.update({
  id: '/child',
  path: '/child',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedParentRoute = AuthenticatedParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ChildIndexRoute = ChildIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChildRoute,
} as any)
const ChildBadgesRoute = ChildBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => ChildRoute,
} as any)
const ChildLearnRoute = ChildLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => ChildRoute,
} as any)
const ChildProgressRoute = ChildProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ChildRoute,
} as any)
const ChildScenarioRoute = ChildScenarioRouteImport.update({
  id: '/scenario',
  path: '/scenario',
  getParentRoute: () => ChildRoute,
} as any)
const ChildScenariosRoute = ChildScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => ChildRoute,
} as any)
const ChildSettingsRoute = ChildSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChildRoute,
} as any)
const ChildTalkRoute = ChildTalkRouteImport.update({
  id: '/talk',
  path: '/talk',
  getParentRoute: () => ChildRoute,
} as any)
const AuthenticatedParentIndexRoute =
  AuthenticatedParentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedParentAlertsRoute =
  AuthenticatedParentAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedParentChaptersRoute =
  AuthenticatedParentChaptersRouteImport.update({
    id: '/chapters',
    path: '/chapters',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedParentControlsRoute =
  AuthenticatedParentControlsRouteImport.update({
    id: '/controls',
    path: '/controls',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedParentPerformanceRoute =
  AuthenticatedParentPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedParentPrivacyRoute =
  AuthenticatedParentPrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedParentProfileRoute =
  AuthenticatedParentProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedParentSettingsRoute =
  AuthenticatedParentSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/child': typeof ChildRouteWithChildren
  '/authenticated/parent': typeof AuthenticatedParentRouteWithChildren
  '/child/badges': typeof ChildBadgesRoute
  '/child/learn': typeof ChildLearnRoute
  '/child/progress': typeof ChildProgressRoute
  '/child/scenario': typeof ChildScenarioRoute
  '/child/scenarios': typeof ChildScenariosRoute
  '/child/settings': typeof ChildSettingsRoute
  '/child/talk': typeof ChildTalkRoute
  '/child/': typeof ChildIndexRoute
  '/authenticated/parent/alerts': typeof AuthenticatedParentAlertsRoute
  '/authenticated/parent/chapters': typeof AuthenticatedParentChaptersRoute
  '/authenticated/parent/controls': typeof AuthenticatedParentControlsRoute
  '/authenticated/parent/performance': typeof AuthenticatedParentPerformanceRoute
  '/authenticated/parent/privacy': typeof AuthenticatedParentPrivacyRoute
  '/authenticated/parent/profile': typeof AuthenticatedParentProfileRoute
  '/authenticated/parent/settings': typeof AuthenticatedParentSettingsRoute
  '/authenticated/parent/': typeof AuthenticatedParentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/child/badges': typeof ChildBadgesRoute
  '/child/learn': typeof ChildLearnRoute
  '/child/progress': typeof ChildProgressRoute
  '/child/scenario': typeof ChildScenarioRoute
  '/child/scenarios': typeof ChildScenariosRoute
  '/child/settings': typeof ChildSettingsRoute
  '/child/talk': typeof ChildTalkRoute
  '/child': typeof ChildIndexRoute
  '/authenticated/parent/alerts': typeof AuthenticatedParentAlertsRoute
  '/authenticated/parent/chapters': typeof AuthenticatedParentChaptersRoute
  '/authenticated/parent/controls': typeof AuthenticatedParentControlsRoute
  '/authenticated/parent/performance': typeof AuthenticatedParentPerformanceRoute
  '/authenticated/parent/privacy': typeof AuthenticatedParentPrivacyRoute
  '/authenticated/parent/profile': typeof AuthenticatedParentProfileRoute
  '/authenticated/parent/settings': typeof AuthenticatedParentSettingsRoute
  '/authenticated/parent': typeof AuthenticatedParentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/child': typeof ChildRouteWithChildren
  '/authenticated/parent': typeof AuthenticatedParentRouteWithChildren
  '/child/badges': typeof ChildBadgesRoute
  '/child/learn': typeof ChildLearnRoute
  '/child/progress': typeof ChildProgressRoute
  '/child/scenario': typeof ChildScenarioRoute
  '/child/scenarios': typeof ChildScenariosRoute
  '/child/settings': typeof ChildSettingsRoute
  '/child/talk': typeof ChildTalkRoute
  '/child/': typeof ChildIndexRoute
  '/authenticated/parent/alerts': typeof AuthenticatedParentAlertsRoute
  '/authenticated/parent/chapters': typeof AuthenticatedParentChaptersRoute
  '/authenticated/parent/controls': typeof AuthenticatedParentControlsRoute
  '/authenticated/parent/performance': typeof AuthenticatedParentPerformanceRoute
  '/authenticated/parent/privacy': typeof AuthenticatedParentPrivacyRoute
  '/authenticated/parent/profile': typeof AuthenticatedParentProfileRoute
  '/authenticated/parent/settings': typeof AuthenticatedParentSettingsRoute
  '/authenticated/parent/': typeof AuthenticatedParentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authenticated'
    | '/auth'
    | '/child'
    | '/authenticated/parent'
    | '/child/badges'
    | '/child/learn'
    | '/child/progress'
    | '/child/scenario'
    | '/child/scenarios'
    | '/child/settings'
    | '/child/talk'
    | '/child/'
    | '/authenticated/parent/alerts'
    | '/authenticated/parent/chapters'
    | '/authenticated/parent/controls'
    | '/authenticated/parent/performance'
    | '/authenticated/parent/privacy'
    | '/authenticated/parent/profile'
    | '/authenticated/parent/settings'
    | '/authenticated/parent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authenticated'
    | '/auth'
    | '/child/badges'
    | '/child/learn'
    | '/child/progress'
    | '/child/scenario'
    | '/child/scenarios'
    | '/child/settings'
    | '/child/talk'
    | '/child'
    | '/authenticated/parent/alerts'
    | '/authenticated/parent/chapters'
    | '/authenticated/parent/controls'
    | '/authenticated/parent/performance'
    | '/authenticated/parent/privacy'
    | '/authenticated/parent/profile'
    | '/authenticated/parent/settings'
    | '/authenticated/parent'
  id:
    | '__root__'
    | '/'
    | '/authenticated'
    | '/auth'
    | '/child'
    | '/authenticated/parent'
    | '/child/badges'
    | '/child/learn'
    | '/child/progress'
    | '/child/scenario'
    | '/child/scenarios'
    | '/child/settings'
    | '/child/talk'
    | '/child/'
    | '/authenticated/parent/alerts'
    | '/authenticated/parent/chapters'
    | '/authenticated/parent/controls'
    | '/authenticated/parent/performance'
    | '/authenticated/parent/privacy'
    | '/authenticated/parent/profile'
    | '/authenticated/parent/settings'
    | '/authenticated/parent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChildRoute: typeof ChildRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated': {
      id: '/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child': {
      id: '/child'
      path: '/child'
      fullPath: '/child'
      preLoaderRoute: typeof ChildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated/parent': {
      id: '/authenticated/parent'
      path: '/parent'
      fullPath: '/authenticated/parent'
      preLoaderRoute: typeof AuthenticatedParentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/child/': {
      id: '/child/'
      path: '/'
      fullPath: '/child/'
      preLoaderRoute: typeof ChildIndexRouteImport
      parentRoute: typeof ChildRoute
    }
    '/child/badges': {
      id: '/child/badges'
      path: '/badges'
      fullPath: '/child/badges'
      preLoaderRoute: typeof ChildBadgesRouteImport
      parentRoute: typeof ChildRoute
    }
    '/child/learn': {
      id: '/child/learn'
      path: '/learn'
      fullPath: '/child/learn'
      preLoaderRoute: typeof ChildLearnRouteImport
      parentRoute: typeof ChildRoute
    }
    '/child/progress': {
      id: '/child/progress'
      path: '/progress'
      fullPath: '/child/progress'
      preLoaderRoute: typeof ChildProgressRouteImport
      parentRoute: typeof ChildRoute
    }
    '/child/scenario': {
      id: '/child/scenario'
      path: '/scenario'
      fullPath: '/child/scenario'
      preLoaderRoute: typeof ChildScenarioRouteImport
      parentRoute: typeof ChildRoute
    }
    '/child/scenarios': {
      id: '/child/scenarios'
      path: '/scenarios'
      fullPath: '/child/scenarios'
      preLoaderRoute: typeof ChildScenariosRouteImport
      parentRoute: typeof ChildRoute
    }
    '/child/settings': {
      id: '/child/settings'
      path: '/settings'
      fullPath: '/child/settings'
      preLoaderRoute: typeof ChildSettingsRouteImport
      parentRoute: typeof ChildRoute
    }
    '/child/talk': {
      id: '/child/talk'
      path: '/talk'
      fullPath: '/child/talk'
      preLoaderRoute: typeof ChildTalkRouteImport
      parentRoute: typeof ChildRoute
    }
    '/authenticated/parent/': {
      id: '/authenticated/parent/'
      path: '/'
      fullPath: '/authenticated/parent/'
      preLoaderRoute: typeof AuthenticatedParentIndexRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/authenticated/parent/alerts': {
      id: '/authenticated/parent/alerts'
      path: '/alerts'
      fullPath: '/authenticated/parent/alerts'
      preLoaderRoute: typeof AuthenticatedParentAlertsRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/authenticated/parent/chapters': {
      id: '/authenticated/parent/chapters'
      path: '/chapters'
      fullPath: '/authenticated/parent/chapters'
      preLoaderRoute: typeof AuthenticatedParentChaptersRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/authenticated/parent/controls': {
      id: '/authenticated/parent/controls'
      path: '/controls'
      fullPath: '/authenticated/parent/controls'
      preLoaderRoute: typeof AuthenticatedParentControlsRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/authenticated/parent/performance': {
      id: '/authenticated/parent/performance'
      path: '/performance'
      fullPath: '/authenticated/parent/performance'
      preLoaderRoute: typeof AuthenticatedParentPerformanceRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/authenticated/parent/privacy': {
      id: '/authenticated/parent/privacy'
      path: '/privacy'
      fullPath: '/authenticated/parent/privacy'
      preLoaderRoute: typeof AuthenticatedParentPrivacyRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/authenticated/parent/profile': {
      id: '/authenticated/parent/profile'
      path: '/profile'
      fullPath: '/authenticated/parent/profile'
      preLoaderRoute: typeof AuthenticatedParentProfileRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/authenticated/parent/settings': {
      id: '/authenticated/parent/settings'
      path: '/settings'
      fullPath: '/authenticated/parent/settings'
      preLoaderRoute: typeof AuthenticatedParentSettingsRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
  }
}

interface AuthenticatedParentRouteChildren {
  AuthenticatedParentAlertsRoute: typeof AuthenticatedParentAlertsRoute
  AuthenticatedParentChaptersRoute: typeof AuthenticatedParentChaptersRoute
  AuthenticatedParentControlsRoute: typeof AuthenticatedParentControlsRoute
  AuthenticatedParentPerformanceRoute: typeof AuthenticatedParentPerformanceRoute
  AuthenticatedParentPrivacyRoute: typeof AuthenticatedParentPrivacyRoute
  AuthenticatedParentProfileRoute: typeof AuthenticatedParentProfileRoute
  AuthenticatedParentSettingsRoute: typeof AuthenticatedParentSettingsRoute
  AuthenticatedParentIndexRoute: typeof AuthenticatedParentIndexRoute
}

const AuthenticatedParentRouteChildren: AuthenticatedParentRouteChildren = {
  AuthenticatedParentAlertsRoute: AuthenticatedParentAlertsRoute,
  AuthenticatedParentChaptersRoute: AuthenticatedParentChaptersRoute,
  AuthenticatedParentControlsRoute: AuthenticatedParentControlsRoute,
  AuthenticatedParentPerformanceRoute: AuthenticatedParentPerformanceRoute,
  AuthenticatedParentPrivacyRoute: AuthenticatedParentPrivacyRoute,
  AuthenticatedParentProfileRoute: AuthenticatedParentProfileRoute,
  AuthenticatedParentSettingsRoute: AuthenticatedParentSettingsRoute,
  AuthenticatedParentIndexRoute: AuthenticatedParentIndexRoute,
}

const AuthenticatedParentRouteWithChildren =
  AuthenticatedParentRoute._addFileChildren(AuthenticatedParentRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedParentRoute: typeof AuthenticatedParentRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedParentRoute: AuthenticatedParentRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ChildRouteChildren {
  ChildBadgesRoute: typeof ChildBadgesRoute
  ChildLearnRoute: typeof ChildLearnRoute
  ChildProgressRoute: typeof ChildProgressRoute
  ChildScenarioRoute: typeof ChildScenarioRoute
  ChildScenariosRoute: typeof ChildScenariosRoute
  ChildSettingsRoute: typeof ChildSettingsRoute
  ChildTalkRoute: typeof ChildTalkRoute
  ChildIndexRoute: typeof ChildIndexRoute
}

const ChildRouteChildren: ChildRouteChildren = {
  ChildBadgesRoute: ChildBadgesRoute,
  ChildLearnRoute: ChildLearnRoute,
  ChildProgressRoute: ChildProgressRoute,
  ChildScenarioRoute: ChildScenarioRoute,
  ChildScenariosRoute: ChildScenariosRoute,
  ChildSettingsRoute: ChildSettingsRoute,
  ChildTalkRoute: ChildTalkRoute,
  ChildIndexRoute: ChildIndexRoute,
}

const ChildRouteWithChildren = ChildRoute._addFileChildren(ChildRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChildRoute: ChildRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
